#List with dictionaries of the 30 cards
deck = [
            {"type": "hero", "name": "The Warrior", "desc": "a great warrior", "health": 20, "str": 9},
            {"type": "hero", "name": "The Sorceror", "desc": "a fearsom sorceror", "health": 25, "str": 5},
            {"type": "hero", "name": "The Archer", "desc": "a sharpshooter", "health": 27, "str": 5},
            {"type": "hero", "name": "The Rogue", "desc": "cunning I guess", "health": 24, "str": 4},
            {"type": "hero", "name": "The Cleric", "desc": "a great healer", "health": 26, "str": 3},
            {"type": "hero", "name": "The Wizard", "desc": "a powerful wizard", "health": 25, "str": 4},
            {"type": "hero", "name": "The Shaman", "desc": "basically a less useful wizard", "health": 25, "str": 5},
            {"type": "hero", "name": "The Paladin", "desc": "huge nerd who narcs on you if you steal anything", "health": 30, "str": 15},
            {"type": "hero", "name": "The Deprived", "desc": "ur fucked m8", "health": 21, "str": 1},
            {"type": "hero", "name": "The Huge Nerd", "desc": "is a huge nerd", "health": 21, "str": 2},
            {"type": "hero", "name": "The Doctor", "desc": "This isnt covered by your HMO", "health": 30, "str": 2},
            {"type": "hero", "name": "The Developer", "desc": "Works on my machine", "health": 5, "str": 4},
            {"type": "hero", "name": "The Bard", "desc": "Better than a slam poet", "health": 20, "str": 2},
            {"type": "hero", "name": "Macho Man Randy Savage", "desc": "Ooohhhhh Yeeeeaaaaahhhh", "health": 28, "str": 10},
            {"type": "hero", "name": "Bing Crosby", "desc": "Beats his kids with sacks of oranges", "health": 28, "str": 10},
            {"type": "spell", "name": "Fireball", "desc": "a sphere of hotness", "str": 2},
            {"type": "spell", "name": "Lightning", "desc": "shocking!", "str": 2},
            {"type": "spell", "name": "Ice Blast", "desc": "like chewing mint gum", "str": 3},
            {"type": "spell", "name": "Summon Monster", "desc": "an otherwordly monster appears and attacks", "str": 4},
            {"type": "spell", "name": "Summon Undead", "desc": "An undead materializes and attacks", "str": 4},
            {"type": "spell", "name": "Scorching Ray", "desc": "A ray of hotness", "str": 5},
            {"type": "spell", "name": "Acid Splash", "desc": "Acid shoots from your finger guns", "str": 6},
            {"type": "spell", "name": "Prestidigitation", "desc": "Amaze them so much they hurt themselves", "str": 7},
            {"type": "spell", "name": "The Big Sad", "desc": "Makes them clinically depressed", "str": 8},
            {"type": "spell", "name": "Special Beam Cannon", "desc": "A beam of energy", "str": 9},
            {"type": "spell", "name": "Metal on Metal", "desc": "its what I crave", "str": 10},
            {"type": "spell", "name": "IRS Audit", "desc": "I hope you saved your receipts", "str": 9},
            {"type": "buff", "name": "Small Health Bonus", "desc": "A small boost to health", "health": 21},
            {"type": "buff", "name": "Medium Health Bonus", "desc": "A moderate boost to health", "health": 23},
            {"type": "buff", "name": "Large Health Bonus", "desc": "A redongdiculous boost to health", "health": 26}
        ]